CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Username] NVARCHAR(50) NOT NULL,
	[Email] NVARCHAR(50) NOT NULL,
	[Password] NVARCHAR(MAX) NOT NULL,
	[Role] INT NOT NULL,
	[Image] NVARCHAR(MAX) NULL,
	[Created_At] DATETIME NOT NULL DEFAULT GETDATE(),
)
